version: '3.8'
services:
  mongo:
    image: mongo
    container_name: footprint-logger-mongo
    restart: always
    env_file:
      - .env.development
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - footprint-logger-dev

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: footprint-logger-app-dev
    ports:
      - '${PORT:-5000}:5000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - footprint-logger-dev
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  footprint-logger-dev:
    driver: bridge
